hrefs:
  - name: historia
    link: https://videeditorial.com.br/historia
  - name: ciencias_sociais
    link: https://videeditorial.com.br/index.php?route=product/category&path=2&
  - name: filosofia
    link: https://videeditorial.com.br/filosofia
  - name: biografias
    link: https://videeditorial.com.br/biografias
  - name: literatura
    link: https://videeditorial.com.br/literatura
  - name: autoconhecimento
    link: https://videeditorial.com.br/autoconhecimento
  - name: economia
    link: https://videeditorial.com.br/economia
  - name: politica
    link: https://videeditorial.com.br/politica
