hrefs:
  - link: https://videeditorial.com.br/index.php?route=product/category&path=74
  - link: https://videeditorial.com.br/literatura-estrangeira
  - link: https://videeditorial.com.br/index.php?route=product/category&path=41
  - link: https://videeditorial.com.br/index.php?route=product/category&path=68
  - link: https://videeditorial.com.br/index.php?route=product/category&path=80
  - link: https://videeditorial.com.br/index.php?route=product/category&path=75
  - link: https://videeditorial.com.br/index.php?route=product/category&path=2
  - link: https://videeditorial.com.br/filosofia
  - link: https://videeditorial.com.br/index.php?route=product/category&path=46
  - link: https://videeditorial.com.br/literatura-brasileira
  - link: https://videeditorial.com.br/index.php?route=product/category&path=37
  - link: https://videeditorial.com.br/index.php?route=product/category&path=92
  - link: https://videeditorial.com.br/index.php?route=product/category&path=58
  - link: https://videeditorial.com.br/index.php?route=product/category&path=124
  - link: https://videeditorial.com.br/index.php?route=product/category&path=72
  - link: https://videeditorial.com.br/literatura
  - link: https://videeditorial.com.br/index.php?route=product/category&path=78
  - link: https://videeditorial.com.br/biografias
  - link: https://videeditorial.com.br/index.php?route=product/category&path=71
  - link: https://videeditorial.com.br/index.php?route=product/category&path=26
  - link: https://videeditorial.com.br/autoconhecimento
  - link: https://videeditorial.com.br/index.php?route=product/category&path=76
  - link: https://videeditorial.com.br/index.php?route=product/category&path=84
  - link: https://videeditorial.com.br/historia
  - link: https://videeditorial.com.br/index.php?route=product/category&path=47